# Site settings
title: Michael Drogalis
email: michael.drogalis@onyxplatform.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaeldrogalis.github.io" # the base hostname & protocol for your site
twitter_username: MichaelDrogalis
github_username:  MichaelDrogalis

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: redcarpet

